"""empty message

Revision ID: a08b886822d7
Revises: a645822aa495
Create Date: 2017-10-01 02:02:22.439947

"""

# revision identifiers, used by Alembic.
revision = 'a08b886822d7'
down_revision = 'a645822aa495'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraintracker_user', sa.Column('one_signal_player_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraintracker_user', 'one_signal_player_id')
    ### end Alembic commands ###
