"""Add role to users. Add requestor name to TowRequestBatch.  Add requestee/or names to TowRequest

Revision ID: 0c7f185f175a
Revises: 6ee5679a642d
Create Date: 2018-01-21 18:01:29.132588

"""

# revision identifiers, used by Alembic.
revision = '0c7f185f175a'
down_revision = '6ee5679a642d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraintracker_user', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('tow_request_batch', sa.Column('requestor_name', sa.String(length=81), nullable=True))
    op.add_column('tow_request', sa.Column('requestor_id', sa.String(length=32), nullable=True))
    op.add_column('tow_request', sa.Column('requestor_name', sa.String(length=81), nullable=True))
    op.add_column('tow_request', sa.Column('requestee_name', sa.String(length=81), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraintracker_user', 'role')
    op.drop_column('tow_request_batch', 'requestor_name')
    op.drop_column('tow_request', 'requestor_id')
    op.drop_column('tow_request', 'requestor_name')
    op.drop_column('tow_request', 'requestee_name')
    ### end Alembic commands ###
