"""empty message

Revision ID: 60939be3aff7
Revises: 0c7f185f175a
Create Date: 2018-03-20 18:55:13.783296

"""

# revision identifiers, used by Alembic.
revision = '60939be3aff7'
down_revision = '0c7f185f175a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraintracker_user', sa.Column('is_android', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraintracker_user', 'is_android')
    ### end Alembic commands ###
