"""empty message

Revision ID: 65edab12f83d
Revises: 1f68819f0b99
Create Date: 2018-04-15 14:37:32.903378

"""

# revision identifiers, used by Alembic.
revision = '65edab12f83d'
down_revision = '1f68819f0b99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tow_event', sa.Column('tow_request_batch_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tow_event', 'tow_request_batch_id')
    ### end Alembic commands ###
