"""empty message

Revision ID: 7b80dc943066
Revises: af7ffeb8acff
Create Date: 2018-04-28 16:02:27.518647

"""

# revision identifiers, used by Alembic.
revision = '7b80dc943066'
down_revision = 'af7ffeb8acff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    #  commands auto generated by Alembic - please adjust! ###
    print("Making request log table")
    op.create_table('terraintracker_request_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('request_url', sa.String(length=2000), nullable=True),
                    sa.Column('request_method', sa.String(length=200), nullable=True),
                    sa.Column('request_query', sa.String(length=2000), nullable=True),
                    sa.Column('request_body', sa.String(length=2000), nullable=True),
                    sa.Column('request_user', sa.String(length=32), nullable=True),
                    sa.Column('remote_ip', sa.String(length=200), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('response_body', sa.String(length=2000), nullable=True),
                    sa.Column('response_code', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    print("Adding time_created column to user")
    op.add_column('terraintracker_user', sa.Column('time_created', sa.DateTime(), nullable=True))
    #  end Alembic commands ###


def downgrade():
    #  commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraintracker_user', 'time_created')
    op.drop_table('terraintracker_request_log')
    #  end Alembic commands ###
