"""Add active_tow_request_batch to User model.

Revision ID: 1f68819f0b99
Revises: 60939be3aff7
Create Date: 2018-04-15 14:23:12.660919

"""

# revision identifiers, used by Alembic.
revision = '1f68819f0b99'
down_revision = '60939be3aff7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraintracker_user', sa.Column('active_tow_request_batch_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'terraintracker_user', 'tow_request_batch', ['active_tow_request_batch_id'], ['id'])
    op.add_column('tow_request_batch', sa.Column('_status', sa.Integer(), nullable=True))
    op.drop_column('tow_request_batch', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tow_request_batch', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tow_request_batch', '_status')
    op.drop_constraint(None, 'terraintracker_user', type_='foreignkey')
    op.drop_column('terraintracker_user', 'active_tow_request_batch_id')
    ### end Alembic commands ###
