"""empty message

Revision ID: 8b79523b4a25
Revises: c7014cac5f98
Create Date: 2018-06-20 03:07:53.711372

"""

# revision identifiers, used by Alembic.
revision = '8b79523b4a25'
down_revision = 'c7014cac5f98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraintracker_boat', sa.Column('_type', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraintracker_boat', '_type')
    ### end Alembic commands ###
