"""empty message

Revision ID: c7014cac5f98
Revises: 9ecaa4d676bb
Create Date: 2018-06-18 05:12:49.223509

"""

# revision identifiers, used by Alembic.
revision = 'c7014cac5f98'
down_revision = '9ecaa4d676bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tow_request', sa.Column('_service_requested', sa.Integer(), nullable=True))
    op.add_column('tow_request_batch', sa.Column('_service_requested', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tow_request_batch', '_service_requested')
    op.drop_column('tow_request', '_service_requested')
    ### end Alembic commands ###
